[project]
name = "externalhound"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "sqlalchemy>=2.0",
    "psycopg2-binary>=2.9",
    "fastapi>=0.128.0",
    "myapplication>=0.1.0",
    "pydantic-settings>=2.12.0",
]
